from sure import expect
from fragdenstaat_client.converter import flatten_item


source = {
    "resource_uri": "https://fragdenstaat.de/api/v1/request/141970/?format=json",
    "id": 141970,
    "url": "/anfrage/kontrollbericht-zu-spatverkauf-magdeburg/",
    "jurisdiction": "https://fragdenstaat.de/api/v1/jurisdiction/1/?format=json",
    "is_foi": True,
    "checked": False,
    "refusal_reason": "",
    "costs": 0.0,
    "public": True,
    "law": "https://fragdenstaat.de/api/v1/law/3/?format=json",
    "description": "1. Wann haben die beiden letzten lebensmittelrechtlichen Betriebs\u00fcberpr\u00fcfungen im folgenden Betrieb stattgefunden:\r\nSp\u00e4tverkauf\r\nWielandstra\u00dfe 11\r\n39108 Magdeburg\r\n\r\n2. Kam es hierbei zu Beanstandungen? Falls ja, beantrage ich hiermit die Herausgabe des entsprechenden Kontrollberichts an mich.",
    "summary": "",
    "same_as_count": 0,
    "same_as": None,
    "due_date": "2019-06-18T00:00:00+02:00",
    "resolved_on": None,
    "last_message": "2019-05-16T09:38:57+02:00",
    "first_message": "2019-05-14T11:01:13.644997+02:00",
    "status": "asleep",
    "public_body": {
        "resource_uri": "https://fragdenstaat.de/api/v1/publicbody/15285/?format=json",
        "id": 15285,
        "name": "Landeshauptstadt Magdeburg - Abt. Veterin\u00e4rwesen und Lebensmittel\u00fcberwachung",
        "slug": "landeshauptstadt-magdeburg-abt-veterinarwesen-und-lebensmitteluberwachung",
        "other_names": "",
        "description": "",
        "url": "http://magdeburg.de/index.php?NavID=37.367&object=adr|37.696.1",
        "depth": 0,
        "classification": None,
        "email": "veterinaerwesen@magdeburg.de",
        "contact": "Telefon +49 391 540-6222\nFax +49 391 540 6211",
        "address": "L\u00fcbecker Stra\u00dfe 32\n39124 Magdeburg",
        "fax": "",
        "request_note": "",
        "number_of_requests": 146,
        "site_url": "https://fragdenstaat.de/behoerde/landeshauptstadt-magdeburg-abt-veterinarwesen-und-lebensmitteluberwachung/",
        "jurisdiction": "https://fragdenstaat.de/api/v1/jurisdiction/13/?format=json",
        "request_note_html": "",
    },
    "resolution": "",
    "slug": "kontrollbericht-zu-spatverkauf-magdeburg",
    "title": "Kontrollbericht zu Sp\u00e4tverkauf, Magdeburg",
    "reference": "food:amenity:92548_1156604969",
    "user": None,
    "project": None,
    "campaign": "https://fragdenstaat.de/api/v1/campaign/4/?format=json",
}


def test_flatten_item():
    result = flatten_item(source)

    expect(result).to.have.key("checked").being.equal("false")
    expect(result).to.have.key("same_as").being.equal("null")
    expect(result).to.have.key("same_as_count").being.equal("0")
    expect(result).to.have.key("costs").being.equal("0.0")
    expect(list(result.keys())).to.equal(
        [
            "resource_uri",
            "id",
            "url",
            "jurisdiction",
            "is_foi",
            "checked",
            "refusal_reason",
            "costs",
            "public",
            "law",
            "description",
            "summary",
            "same_as_count",
            "same_as",
            "due_date",
            "resolved_on",
            "last_message",
            "first_message",
            "status",
            "institution_resource_uri",
            "institution_id",
            "institution_name",
            "institution_slug",
            "institution_other_names",
            "institution_description",
            "institution_url",
            "institution_depth",
            "institution_classification",
            "institution_email",
            "institution_contact",
            "institution_address",
            "institution_fax",
            "institution_request_note",
            "institution_number_of_requests",
            "institution_site_url",
            "institution_jurisdiction",
            "institution_request_note_html",
            "resolution",
            "slug",
            "title",
            "reference",
            "user",
            "project",
            "campaign",
        ]
    )
